FROM mcr.microsoft.com/playwright:v1.54.1-jammy

WORKDIR /tests

# Install Playwright Test
RUN npm init -y && npm install -D @playwright/test

# Copy your test file(s)
COPY tests/ .

# Run test
CMD ["npx", "playwright", "test", "test.spec.ts"]

