FROM nginx:alpine

# You're replacing the default Nginx setup with your own rules about how to serve the site.
COPY nginx/default.conf /etc/nginx/conf.d/default.conf 

# Copy all the files in my app/ folder into the web server’s public folder where defined in nginx/default.conf
COPY app/ /usr/share/nginx/html

