services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
  
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    depends_on:
      - nginx
